export default {
  at: "2024-06-27T15:48:31.860Z",
  products: [
    {
      description: "reprehenderit id dolore nisi",
      name: "ex",
      price: 1481.13,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {
      description: "officia id adipisicing tempor",
      name: "id",
      price: 1187.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {
      description: "aute ullamco adipisicing irure",
      name: "ut",
      price: 686.5,
      tmpProperty: undefined,
      activePromoId: 97,
    },
    {
      description: "amet laboris veniam ex",
      name: "Lorem",
      price: 1933.74,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laborum exercitation laboris amet",
      name: "ad",
      price: 1706.41,
      tmpProperty: undefined,
      activePromoId: 15,
    },
    {
      description: "nisi aliqua deserunt elit",
      name: "cillum",
      price: 989.19,
      tmpProperty: undefined,
      activePromoId: 61,
    },
    {},
    {},
    {},
    {
      description: "ex cillum sunt culpa",
      name: "pariatur",
      price: 1903.5,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {
      description: "pariatur minim tempor ex",
      name: "ut",
      price: 392.85,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "culpa ut qui magna",
      name: "tempor",
      price: 1557.68,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim ad esse cupidatat",
      name: "eiusmod",
      price: 821.71,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "exercitation culpa consequat mollit",
      name: "adipisicing",
      price: 740.25,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {},
    {},
    {},
    {
      description: "ut esse culpa laborum",
      name: "ea",
      price: 1876.55,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "pariatur dolore officia mollit",
      name: "aliqua",
      price: 1840.72,
      tmpProperty: undefined,
      activePromoId: 63,
    },
    {
      description: "officia sint et proident",
      name: "irure",
      price: 1242.71,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "est aliquip amet ullamco",
      name: "labore",
      price: 736.56,
      tmpProperty: undefined,
      activePromoId: 10,
    },
    {
      description: "culpa do ipsum occaecat",
      name: "amet",
      price: 1938.37,
      tmpProperty: undefined,
      activePromoId: 33,
    },
    {
      description: "aliquip reprehenderit ad culpa",
      name: "Lorem",
      price: 534.78,
      tmpProperty: undefined,
      activePromoId: 94,
    },
    {
      description: "qui dolore reprehenderit dolore",
      name: "velit",
      price: 1836.81,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: "velit adipisicing eu eiusmod",
      name: "commodo",
      price: 1544.27,
      tmpProperty: undefined,
      activePromoId: 84,
    },
    {
      description: "reprehenderit sint dolore veniam",
      name: "enim",
      price: 900.2,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "incididunt cillum tempor tempor",
      name: "labore",
      price: 1842.17,
      tmpProperty: undefined,
      activePromoId: 57,
    },
    {
      description: "aute dolore ullamco sint",
      name: "est",
      price: 1659.15,
      tmpProperty: undefined,
      activePromoId: 7,
    },
    {
      description: "ea dolor ea dolore",
      name: "dolor",
      price: 1929.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "amet quis reprehenderit esse",
      name: "dolore",
      price: 156.73,
      tmpProperty: undefined,
      activePromoId: 51,
    },
    {
      description: "Lorem officia quis culpa",
      name: "labore",
      price: 235.29,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {
      description: "est nulla commodo voluptate",
      name: "consectetur",
      price: 1620.72,
      tmpProperty: undefined,
      activePromoId: 89,
    },
    {
      description: "magna est eu eu",
      name: "minim",
      price: 219.01,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laboris ea elit fugiat",
      name: "labore",
      price: 894.1,
      tmpProperty: undefined,
      activePromoId: 15,
    },
    {
      description: "elit velit pariatur culpa",
      name: "fugiat",
      price: 1552.34,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "labore aute duis incididunt",
      name: "Lorem",
      price: 1913.26,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "elit officia veniam tempor",
      name: "nulla",
      price: 1178.91,
      tmpProperty: undefined,
      activePromoId: 94,
    },
    {
      description: "labore commodo enim officia",
      name: "aliqua",
      price: 1694.9,
      tmpProperty: undefined,
      activePromoId: 16,
    },
    {},
    {},
    {},
    {
      description: "ea tempor ex sunt",
      name: "et",
      price: 1392.21,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu nulla consequat esse",
      name: "ex",
      price: 1170.23,
      tmpProperty: undefined,
      activePromoId: 81,
    },
    {
      description: "magna fugiat ullamco nisi",
      name: "reprehenderit",
      price: 927.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "quis occaecat excepteur ipsum",
      name: "commodo",
      price: 692.74,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "duis in dolore consectetur",
      name: "ipsum",
      price: 886.99,
      tmpProperty: undefined,
      activePromoId: 15,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "dolore commodo tempor eiusmod",
      name: "in",
      price: 415.67,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat dolor sunt eiusmod",
      name: "est",
      price: 303.41,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "elit ipsum quis do",
      name: "do",
      price: 384.28,
      tmpProperty: undefined,
      activePromoId: 58,
    },
    {
      description: "tempor minim sunt mollit",
      name: "pariatur",
      price: 169.88,
      tmpProperty: undefined,
      activePromoId: 18,
    },
    {
      description: "deserunt exercitation quis fugiat",
      name: "ipsum",
      price: 1894.07,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laboris nostrud aute laborum",
      name: "adipisicing",
      price: 1853.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor nisi esse amet",
      name: "exercitation",
      price: 1532.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliquip irure dolor pariatur",
      name: "culpa",
      price: 1415.2,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: "veniam ad aliqua nulla",
      name: "anim",
      price: 1459.71,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "officia consectetur irure proident",
      name: "id",
      price: 1119.53,
      tmpProperty: undefined,
      activePromoId: 89,
    },
    {
      description: "exercitation ea nostrud tempor",
      name: "anim",
      price: 1252.63,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor est tempor nostrud",
      name: "exercitation",
      price: 529.64,
      tmpProperty: undefined,
      activePromoId: 96,
    },
    {
      description: "ea sint elit sint",
      name: "consequat",
      price: 331.56,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex ut sit exercitation",
      name: "laboris",
      price: 769.47,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam do ut mollit",
      name: "Lorem",
      price: 684.73,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "elit sint incididunt enim",
      name: "et",
      price: 1532.54,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: "enim ut et nostrud",
      name: "anim",
      price: 559.83,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis nulla aliquip duis",
      name: "amet",
      price: 1225.97,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "Lorem quis minim ullamco",
      name: "anim",
      price: 209.18,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "do non dolore ea",
      name: "quis",
      price: 501.88,
      tmpProperty: undefined,
      activePromoId: 43,
    },
    {
      description: "tempor duis laborum sit",
      name: "irure",
      price: 351.63,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "amet et in laborum",
      name: "consectetur",
      price: 1268.8,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sit non nostrud laborum",
      name: "aliqua",
      price: 928.34,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "non aliquip esse eu",
      name: "elit",
      price: 714.34,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aute cillum aliqua tempor",
      name: "reprehenderit",
      price: 293.59,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu ut veniam tempor",
      name: "cillum",
      price: 183.78,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "non proident anim est",
      name: "dolore",
      price: 1507,
      tmpProperty: undefined,
      activePromoId: 56,
    },
    {
      description: "voluptate aute sint anim",
      name: "excepteur",
      price: 1953.72,
      tmpProperty: undefined,
      activePromoId: 17,
    },
    {
      description: "reprehenderit Lorem irure sit",
      name: "culpa",
      price: 248.63,
      tmpProperty: undefined,
      activePromoId: 77,
    },
    {
      description: "proident minim culpa nisi",
      name: "ad",
      price: 1697.63,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cillum et excepteur anim",
      name: "aute",
      price: 1210.95,
      tmpProperty: undefined,
      activePromoId: 22,
    },
    {
      description: "sint est reprehenderit fugiat",
      name: "voluptate",
      price: 484.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "exercitation velit est laborum",
      name: "pariatur",
      price: 1023.96,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laborum duis fugiat aliquip",
      name: "esse",
      price: 847.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ut deserunt elit labore",
      name: "do",
      price: 796.55,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "do occaecat laboris ullamco",
      name: "aute",
      price: 289.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint dolore non elit",
      name: "mollit",
      price: 718.74,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat irure eiusmod ad",
      name: "quis",
      price: 546.44,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "irure magna tempor minim",
      name: "sunt",
      price: 1628.3,
      tmpProperty: undefined,
      activePromoId: 78,
    },
    {
      description: "exercitation consequat dolor sint",
      name: "nisi",
      price: 897.94,
      tmpProperty: undefined,
      activePromoId: 96,
    },
    {
      description: "ex do laborum exercitation",
      name: "sit",
      price: 1117.22,
      tmpProperty: undefined,
      activePromoId: 4,
    },
    {
      description: "eu eu amet eiusmod",
      name: "eu",
      price: 1365.68,
      tmpProperty: undefined,
      activePromoId: 96,
    },
    {
      description: "sit ea est ad",
      name: "ut",
      price: 690.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate qui reprehenderit irure",
      name: "eiusmod",
      price: 410.94,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliqua tempor ea tempor",
      name: "nulla",
      price: 824.75,
      tmpProperty: undefined,
      activePromoId: 96,
    },
    {
      description: "esse commodo cillum incididunt",
      name: "anim",
      price: 1605.48,
      tmpProperty: undefined,
      activePromoId: 96,
    },
    {
      description: "occaecat culpa ipsum anim",
      name: "et",
      price: 1356.59,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu incididunt consequat laboris",
      name: "minim",
      price: 1513.1,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "sint incididunt aliqua proident",
      name: "esse",
      price: 775.82,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ea eu ea culpa",
      name: "eiusmod",
      price: 287.94,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eiusmod anim nostrud ullamco",
      name: "officia",
      price: 1033.64,
      tmpProperty: undefined,
      activePromoId: 40,
    },
    {
      description: "cupidatat sit duis laboris",
      name: "irure",
      price: 979.11,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: "sit incididunt tempor magna",
      name: "esse",
      price: 1904.45,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {
      description: "dolor elit aliquip sit",
      name: "aute",
      price: 1869.26,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ut ad consectetur labore",
      name: "ea",
      price: 562.72,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ullamco aute exercitation exercitation",
      name: "aliquip",
      price: 1847.35,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis commodo deserunt elit",
      name: "laborum",
      price: 423.99,
      tmpProperty: undefined,
      activePromoId: 47,
    },
    {
      description: "nisi proident anim consectetur",
      name: "proident",
      price: 1668.94,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: "qui sit laboris laborum",
      name: "dolore",
      price: 1100.73,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "deserunt proident nostrud minim",
      name: "do",
      price: 1265.83,
      tmpProperty: undefined,
      activePromoId: 61,
    },
    {
      description: "voluptate nostrud deserunt enim",
      name: "labore",
      price: 1041.07,
      tmpProperty: undefined,
      activePromoId: 34,
    },
    {
      description: "veniam aute ex laboris",
      name: "nulla",
      price: 920.6,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "pariatur sint eu laboris",
      name: "nisi",
      price: 1025.85,
      tmpProperty: undefined,
      activePromoId: 28,
    },
  ],
};
